---
kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: minitwitter
spec:
  ports:
  - name: http
    port: 8090
    targetPort: 8090
  selector:
    app: minitwitter
  type: NodePort