apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: minitwitter
    version: testing
  name: minitwitter-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minitwitter
      version: testing
  template:
    metadata:
      labels:
        app: minitwitter
        version: testing
    spec:
      containers:
      - command:
        - "/app/twitter-clone" 
        - "-configfile"
        - "/etc/servicejson/properties.json"
        image: twitter-clone:latest
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Accept
              value: application/json
            path: /
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: minitwitter
        ports:
        - containerPort: 8090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Accept
              value: application/json
            path: /
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/servicejson
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: configfile